### ISSUE TITLE
Marid5.zip login in Firefox

### ISSUE THREAD

**Issue by jpavlo** [maridco/marid#1]
have you test it in Firefox? something is wrong with login button, help i can´t see anything in Firebug.

**Comment by nb333** [comment]
Yes, I had an issue with the login as well. I thought it could have been caused by one of the add-ons - didn't try disabling them though.

**Comment by jpavlo** [comment]
ok, to not duplicate work, i´m on it, ok?

**Comment by nb333** [comment]
Yeah, that's fine. :D

**Comment by jpavlo** [comment]
Lines commented now works in Firefox. bootstrap.marid.css

/_.root{
  -webkit-animation: fadeIn 3s;
  animation: fadeIn 3s;
}_/

**Comment by mbmjertan** [comment]
Try adding -moz-animation: fadeIn 3s; and see if that helps.

**Comment by jpavlo** [comment]
No, it did´t work, but i added Animate.css from http://daneden.github.io/animate.css/ and tested in FF, Chrome, Safari.
